### ISSUE TITLE
Add Resume as a page-Feature request

### ISSUE THREAD

**Issue by abhigenie92** [AmmsA/theresumator#23]
Would it be possible to add resume as page. This should appear along side About .. and rest of pages. On clicking on Resume it should guide one to a pdf of the Resume.

**Comment by AmmsA** [comment]
An automated pdf version of the website you mean? I'm a bit hesitant if that's the case because the feature would be a little tricky to implement. I want this app to be as light weight as possible.
If you feel like you can implement this elegently, feel free to do so and make a pull request. 

Meanwhile, I made a new resume button just below the about button that is meant to link to the user exisitng pdf url.

**Comment by abhigenie92** [comment]
Thanks! I was referring to the second option of resume button only.
I followed your instructions while deploying. How can Update the deployment of heroku to include the new Resume feature?
And if possible please also mention how can I change the code of the deployment. It isn't linked directly to any github repo?

**Comment by AmmsA** [comment]
If you click the deploy button now, it will have the resume button feature (you just need to update the link in your admin page for the button to show).

It is. This repo uses the django-resumetor app, but not the master branch. It uses a special branch designed for easier deployment to heroku. See
https://github.com/AmmsA/theresumator/blob/master/requirements.txt#L7

Out of curiosity, what changes would you like to make to the source code?

**Comment by abhigenie92** [comment]
Thanks for the reply! But I want to deploy to an existing project. Using what you said I will deploy to a new project. 

Accessing the code:
With, it clones to an empty repository.  
```
$ heroku login
$ heroku git:clone -a <project_name>
```
Maybe trying to make the sidebar stay at the place as the page scrolls down.

**Comment by abhigenie92** [comment]
Hi, If possible can you please provide instructions on how to access and modify the website code deployed by the clicking on the deploy button in the Readme file.

**Comment by AmmsA** [comment]
You should read the  [heroku's documentation ](https://devcenter.heroku.com/articles/heroku-button) on this.

You'll need to fork this repo, and the [django-resumator](https://github.com/AmmsA/django-resumator/) repo. Make the django related changes and cutomization (of models, templates, etc) you want in your fork of django-resumator, and make sure it works. Then in your fork of this repo, update https://github.com/AmmsA/theresumator/blob/master/requirements.txt#L7 and update https://github.com/AmmsA/theresumator/blob/master/app.json accordingly.

**Comment by abhigenie92** [comment]
thanks!
