### ISSUE TITLE
Publication page, addition of tags- Feature Request

### ISSUE THREAD

**Issue by abhigenie92** [AmmsA/theresumator#25]
It would be great if there tags for the publications to make it easier for someone to view.
For example: as on this page http://ai.stanford.edu/users/koller/papers.cgi

Also, if possible the abstract section could be dynamic. That is, be minimized by default and open up on clicking.

**Comment by AmmsA** [comment]
Again, the feature request is more related to [django-resumator](https://github.com/AmmsA/django-resumator). Please move there.
